name: haw
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:

  flutter:
    sdk: flutter
  getwidget: ^4.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  percent_indicator: ^4.0.1
  http: ^1.1.0
#  syncfusion_flutter_calendar: ^24.1.43
  syncfusion_flutter_calendar: 23.2.4
  scrollable_clean_calendar: ^1.4.1
  numberpicker: ^2.1.2
  intl: 0.18.1
  google_sign_in: ^6.2.1
  dropdown_textfield: ^1.0.8
  shared_preferences: ^2.2.2
  clean_calendar: ^1.1.0
#  syncfusion_flutter_datepicker: ^24.1.44
  syncfusion_flutter_datepicker: 23.2.4
  syncfusion_flutter_charts: ^23.2.7
  firebase_auth: 4.16.0
  firebase_core: ^2.24.2
#  flutter_launcher_icons: ^0.13.1
  local_auth: ^2.1.8
  flutter_pin_code_widget: ^0.1.0
  pinput: ^3.0.1
  dio: ^5.4.0
  file_picker: ^6.1.1
  mime_type: ^1.0.0
  image_picker: ^1.0.7
  http_multi_server: ^3.2.1
  webview_flutter: ^4.7.0
  flutter_date_range_picker: ^0.0.14


#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: false
#  image_path: "assets/icon/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/